# Generated by Django 4.1.7 on 2023-04-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='activation_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='activation_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
